### ISSUE TITLE
M3U displayed in wrong order but played in correct order

### ISSUE THREAD

**Issue by warwickmm** [xbmc/Official-Kodi-Remote-iOS#204]
This occurs with Kodi Remote version 1.6.1.  I didn't experience this issue with 1.5.7.

I have an M3U playlist where all the entries are flac music files.  If I short-press on the playlist to view the entries without playing them, the order of the entries does not match that of the playlist.  However, if I long-press on the playlist and start playing it, the queued entries are in the correct order.

Example of M3U file:
```
#EXTCPlayListM3U::M3U
#EXTINF:0,22. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act II, Scene I. Cavatina: Porgi, amor, qualche ristoro
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/22 - Le Nozze di Figaro, K. 492: Act II, Scene I. Cavatina: Porgi, amor, qualche ristoro.flac
#EXTINF:0,25. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act II, Scene III. Canzona: Voi che sapete che cosa e amor
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/25 - Le Nozze di Figaro, K. 492: Act II, Scene III. Canzona: Voi che sapete che cosa e amor.flac
#EXTINF:0,53. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act III, Scene VIII. Aria: Dove sono i bei momenti
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/53 - Le Nozze di Figaro, K. 492: Act III, Scene VIII. Aria: Dove sono i bei momenti.flac
#EXTINF:0,55. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act III, Scene X. Duetto: Che soave zeffiretto
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/55 - Le Nozze di Figaro, K. 492: Act III, Scene X. Duetto: Che soave zeffiretto.flac
#EXTINF:0,72. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act IV, Scene X. Aria: Deh vieni, non tardar, o gioia bella
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/72 - Le Nozze di Figaro, K. 492: Act IV, Scene X. Aria: Deh vieni, non tardar, o gioia bella.flac
#EXTINF:0,78. Wolfgang Amadeus Mozart - Le Nozze di Figaro, K. 492: Act IV, Scene XIV. Gente, gente, all'armi, all'armi
<base path>/Le Nozze di Figaro, K. 492 (Orchester und Chor der Deutschen Oper Berlin with Karl Böhm (conductor))/78 - Le Nozze di Figaro, K. 492: Act IV, Scene XIV. Gente, gente, all'armi, all'armi.flac
#EXTINF:0,42. Wolfgang Amadeus Mozart - Don Giovanni, K. 527: Act II, Scene III. Canzonetta: Deh, vieni alla finestra
<base path>/Don Giovanni, K. 527 (Berlin Philharmonic with Herbert von Karajan (conductor))/42 - Don Giovanni, K. 527: Act II, Scene III. Canzonetta: Deh, vieni alla finestra.flac
#EXTINF:0,65. Wolfgang Amadeus Mozart - Don Giovanni, K. 527: Act II, Scene XV. Finale: Don Giovanni, a cenar teco m'invitasti
<base path>/Don Giovanni, K. 527 (Berlin Philharmonic with Herbert von Karajan (conductor))/65 - Don Giovanni, K. 527: Act II, Scene XV. Finale: Don Giovanni, a cenar teco m'invitasti.flac
#EXTINF:0,05. Wolfgang Amadeus Mozart - Die Zauberflöte, K. 620: Act I, Scene IV. Arie: Dies Bildnis ist bezaubernd schön.flac
<base path>/Die Zauberflöte, K. 620 (Academy of St. Martin in the Fields with Sir Neville Marriner (conductor))/05 - Die Zauberflöte, K. 620: Act I, Scene IV. Arie: Dies Bildnis ist bezaubernd schön.flac
#EXTINF:0,22. Wolfgang Amadeus Mozart - Die Zauberflöte, K. 620: Act II, Scene I. Arie: mit Chor O Isis und Osiris.flac
<base path>/Die Zauberflöte, K. 620 (Academy of St. Martin in the Fields with Sir Neville Marriner (conductor))/22 - Die Zauberflöte, K. 620: Act II, Scene I. Arie: mit Chor O Isis und Osiris.flac
```

List of entries from short-press (order doesn't match M3U file):

![display](https://user-images.githubusercontent.com/17345532/112248768-be4e4580-8c13-11eb-8439-2e7cef01cbb1.png)

Queued entries from long-press (order matches M3U file):

![playing](https://user-images.githubusercontent.com/17345532/112248783-c5755380-8c13-11eb-9596-d670fcf0b674.png)

**Comment by wutschel** [comment]
Thanks for reporting. I can reproduce wrong sorting with the current test build on TestFlight (1.6.2 Build 2124). Which version did you use for your tests?

If you also use the test version, your issue is most likely fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/199. At least for me the playlist sorting is matching the playback order after applying the PR.

**Comment by warwickmm** [comment]
Thanks.  I tested with version 1.6.1.  I will wait for the patch from #199 to appear in a release.  :+1:

**Comment by wutschel** [comment]
Ok. Just to make sure I am looking at the right stuff: I was just checking with 1.6.1 from AppStore. With this version I do not see the problem you describe. Only with the App installed from TestFlight (1.6.2 Build 2124) I observe this. To figure this out just press the Kodi icon on the connection/server screen. This will show an info screen also mentioning the App version, e.g. `v1.6.1 (2070)`.

**Comment by warwickmm** [comment]
Thank you.  My app says v1.6.1 (2070).  I installed testflight v1.6.2 (2124) and confirmed that the issue still exists.  I can wait for the testflight with the changes from #199 and report back here.

**Comment by wutschel** [comment]
Really interesting, I wasn´t expecting the issue was already existing in 1.6.1, and I hope this is not a different problem as I have fixed. Let´s see.

Another question: In your error report you state

> List of entries from short-press

I enter the playlist menu from the menu ("Music" > "..." > Music Playlists""). When I perform a short-press on a playlist I get an action menu and can select different options, also just showing the content. This is what I did to check for displaying without playing. I cannot short-press and get such list directly. Are you having a different use case?

**Comment by warwickmm** [comment]
Sorry, I forgot to mention some important details.  The m3u playlist resides on my NAS, which is accessed via an NFS media source.  I was listing the playlist entries by going to "Music" > [folder icon] > [media source] > [folder with playlists].  There, if I short-press on a playlist, I am presented with a screen with the playlist entries (first screenshot above).

I remember experiencing this issue several years ago, then noticing that it appeared to be fixed in 1.5.7 (or possibly earlier).  Then, I noticed the possible regression in 1.6.1.

**Comment by wutschel** [comment]
And there we go. I can see this as well via your use case, and it is not fixed by #199. In fact, the items come already from Kodi server sorted like this -- by name/label. And this makes sense in general, as this is a file browser menu. Removing the sorting request helps to properly display the m3u content, but lets the other items (e.g. folders and filenames) unsorted.

What you could do, is to move the m3u file to the local playlist folder on your Kodi machine and call it via "Music" > "..." > "Music Playlists". This will show the correct sorting with 1.6.1 (and for 1.6.2 when the fix #199 is applied). As a goodie on top it will show the cover art in the preview as well.

**Comment by howie-f** [comment]
> Is there a way to check for the type of item which is displayed, e.g. "playlist", "file" or "folder"?

assuming they fetched by (test example Files.GetDirectory is the key i hope)
```
{"jsonrpc":"2.0",
  "method":"Files.GetDirectory",
  "id":-2008553762,"params":{"media":"music","directory":"\/mnt\/media\/music\/",
  "sort":{"order":"ascending","method":"label","ignorearticle":false}}}
```
i get the response `..."file":"/mnt/media/music/diverses/","filetype":"directory"...`
also saw `..."filetype":"file"...` when i queried a different directory containing files.
but i don't have a single playlist here to see what happens then. would assume it is also file

**Comment by warwickmm** [comment]
Thanks @wutschel, that makes sense.  I copied the playlists over to Kodi and verified that navigating to "Music" > "..." > "Music Playlists" with v1.6.2 (2124), the sort order is incorrect (without #199).  After reverting back to 1.6.1, the sort order is correct.

Please ignore my comment about this not being an issue in prior versions.  Accessing the playlist through the file browser is something I have only done recently, hence the different behavior.

**Comment by wutschel** [comment]
> assuming they are fetched by (test example Files.GetDirectory is the key i hope)
> but i don't have a single playlist here to see what happens then. would assume it is also file

Thanks. And yes, Files.GetDirectory is used. I checked this yesterday and for playlists also "directory" is reported. I see no obvious and good way to differentiate this. Checking the suffix of the filename is just another special treatment on the one hand. On the other hand the playlist´s content is having the key "id" which we could identify and then change the sorting. But what do we do with mixed content, e.g. having songs (with "id") and folder/files (w/o "id"). I just think this is overcomplicating the logic.

**Comment by warwickmm** [comment]
It sounds like there's no clean solution to this, so if it's not worth the effort please feel free to close this issue.  The important thing is that the songs are queued in the correct order, which they are.

**Comment by wutschel** [comment]
@kambala-decapitator, can you close this one? I do not see a way to rework this with reasonable effort.
